//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Single SteeringTrigger
        {
            get
            {
                return SteamVR_Actions.default_SteeringTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean PointingRayActivate
        {
            get
            {
                return SteamVR_Actions.default_PointingRayActivate;
            }
        }
        
        public virtual SteamVR_Action_Boolean PointingRayDragging
        {
            get
            {
                return SteamVR_Actions.default_PointingRayDragging;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapRight
        {
            get
            {
                return SteamVR_Actions.default_SnapRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TimerAction
        {
            get
            {
                return SteamVR_Actions.default_TimerAction;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleActive
        {
            get
            {
                return SteamVR_Actions.default_TeleActive;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleConfirm
        {
            get
            {
                return SteamVR_Actions.default_TeleConfirm;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
